### ISSUE TITLE
Ability to listen on external IP address, not just localhost

### ISSUE THREAD

**Issue by rickhuizinga** [mklabs/tiny-lr#17]
It would be great if tiny-lr could listen for clients connecting from an external IP, rather than just localhost.

I use a Chromebook and a remote virtual machine for development.  The source files are modified on the remote virtual machine, and I use my local browser.  It appears that LiveReload assumes that the server and client are both on the same machine, which is not the case in this scenario.

**Comment by wayne-o** [comment]
The manual tag approach didn't work for me? Is there another way to get this working?

**Comment by t1bb4r** [comment]
I'll create another issue if this wasn't the intention of the original poster.

I have an issue where I need to listen on localhost instead of all interfaces, because the port is already in use on another interface and I can't change the port for a very long and specific reason.

The following code is where my problem is [server.js:66-74](https://github.com/mklabs/tiny-lr/blob/master/lib/server.js#L66-L74). I would like to do tinyrl.listen(port, address) and have the function pass the address to the http.createServer part.

I don't mind making a pull request as I'm going to fork and work on it either way.
